### ISSUE TITLE
Schema::TYPE_TEXT is too short in MySQL

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/db-mysql#2]
`Schema::TYPE_TEXT` converts to TEXT in MySQL. This is just 64K, which is not a lot. Unless it's in strict mode, MySQL will truncate anything longer when inserting, and not throw an error (it'll throw a warning, but you'll have to look in the mysql server log).
You can use MEDIUMTEXT and LONGTEXT for your fields, but that only works in MySQL, and not in Postgre and Sqlite for example (where TEXT is long enough), so if you're writing portable code, you can't just use `'MEDIUMTEXT'`.
It's also likely that most developers will just use Yii's schema types, without knowing that the data is limited to 64K.

I see several possible solutions to this:
1. Adding Schema::TYPE_MEDIUMTEXT and Schema::TYPE_LONGTEXT, similar to how we have TYPE_INTEGER and TYPE_BIGINT. This probably breaks BC, because custom QueryBuilders will be missing these types, and it also makes the typeMap more bloated, just because of a quirk in MySQL (unlike bigint, which is present in other databases). A developer using Postgre might not even care, since they won't have problems with TYPE_TEXT. I don't think this is a good solution.
2. Changing `\yii\db\mysql\QueryBuilder::$typeMap[Schema::TYPE_TEXT]` to `'MEDIUMTEXT'` or `'LONGTEXT'`. This adds 1 or 2 extra bytes per field per row, which can add up if you have a lot of rows, but in typical use cases shouldn't matter much. It's better to have a safe default, and let those who know the trade-offs optimize it. This change would cause inconsistency in existing databases (fields that were created before the change would remain TEXT, new ones would become MEDIUMTEXT, while rebuilding the database using the new version would create all MEDIUMTEXT).
3. Making the default configurable. You could have a setting that determines globally what Schema::TYPE_TEXT will be converted to in MySQL. You could default this to 'TEXT' for BC, but I think it would be a good idea to default it to 'MEDIUMTEXT' (maybe in Yii 2.1?).

I'm going to change the default to MEDIUMTEXT for my projects, overwriting the typeMap in mysql\QueryBuilder. Unfortunately, the query builder is [not created using Yii::createObject](https://github.com/yiisoft/yii2/blob/2.0.4/framework/db/mysql/Schema.php#L84), so I can't use DI to do this, and I'll have to extend both \yii\db\mysql\Schema and \yii\db\mysql\QueryBuilder, <s>then overwrite the db connection's schemaMap (and I can't change just the mysql schema in the application configuration, I have to replace the whole thing). This is really inconvenient. Is there a better way to do this?</s> I can use DI to replace the Schema at least.

**Comment by Tigrov** [comment]
Can be solved using `$size` argument for `ColumnBuilder::text()` method. Then generate db type depends on the size.

**Comment by Tigrov** [comment]
Checked, if size is specified, type will be created depending on size.

For example, use `ColumnBuilder::text(100_000)` for `MEDUIMTEXT` type

From the documentation:
`An optional length M can be given for this type. If this is done, MySQL creates the column as the smallest TEXT type large enough to hold values M characters long.`

https://dev.mysql.com/doc/refman/8.4/en/string-type-syntax.html

**Comment by Tigrov** [comment]
Tests and doc will be added

**Comment by Tigrov** [comment]
Doc and tests are added
https://github.com/yiisoft/db/blob/4f9a12a01d93bcffe3e4fecc23c53ff86d70dd43/src/Schema/Column/ColumnBuilder.php#L156-L176
