### ISSUE TITLE
MySQL loadColumnSchema: determine boolean columns

### ISSUE THREAD

**Issue by vitalcrazz** [yiisoft/db-mysql#3]
The method `loadColumnSchema` determines a column as a boolean only if db type is 'BIT(1)'.
https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/Schema.php#L160

At the same time Schema::TYPE_BOOLEAN maps on 'tinyint(1)' for MySQL.
https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L41

The method `loadColumnSchema` for MS SQL is implemented in the right way. It considers both TINYINT(1) and BIT(1) types.
https://github.com/yiisoft/yii2/blob/master/framework/db/mssql/Schema.php#L203

**I propose** to change the line 160 in mysql/Schema.php to make it corresponding to the same method for MS SQL. After that the data types mapping will be proper.

`if ($column->size === 1 && ($type === 'tinyint' || $type === 'bit')) {`

This issue isn't theoretical. I created a migration with boolean column. Then I used gii to generate CRUD. But it generates a textField for boolean colums (not checkbox!). And it's not a gii fault, it's all about implementation of loadColumnSchema method for MySQL.

**Comment by terabytesoftw** [comment]
Fixed.
