### ISSUE TITLE
MySQL wrong boolean type should be bit(1)

### ISSUE THREAD

**Issue by machour** [yiisoft/db-mysql#4]
A while ago (8ecceb3), it was decided that Yii2 won't treat `tinyint(1)` as a boolean meta-type for MySQL.

It seems however that Yii stills generates `tinyint(1)` when given a boolean in migrations:
  https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L41

I think that it should be changed to `bit(1)` as it's the solely recognized boolean type for MySQL in `loadColumnSchema`.

**Comment by terabytesoftw** [comment]
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-19.html

"Display width specification for integer data types was deprecated in MySQL 8.0.17, and now statements that include data type definitions in their output no longer show the display width for integer types, with these exceptions:

The type is TINYINT(1). MySQL Connectors make the assumption that TINYINT(1) columns originated as BOOLEAN columns; this exception enables them to continue to make that assumption.

The type includes the ZEROFILL attribute.

This change applies to tables, views, and stored routines, and affects the output from SHOW CREATE and DESCRIBE statements, and from INFORMATION_SCHEMA tables."

**Comment by xandros15** [comment]
My mariadb database got column tinyint(1) where I'm holding numbers from 0-7. 
Because of that change when I'm trying to use ActiveRecord to save model with other values than 0 always got 1 in database. 
Is there any option to control value types as I want?
